version: 2.1

orbs:
  cit:
    version: 2.1
    description: "sample inline orb"
    commands:
      bundler-preamble:
        steps:
          - run: bundle -v
    jobs:
      rspec-run:
        parameters:
          envvar1:
            type: string
            description: value for SAMPLE_ENV_VAR1
          envvar2:
            type: string
            description: value for SAMPLE_ENV_VAR2
          envvar3:
            type: string
            description: value for SAMPLE_ENV_VAR3
        executor: default
        environment:
          SAMPLE_ENV_VAR1: << parameters.envvar1 >>
          SAMPLE_ENV_VAR2: << parameters.envvar2 >>
          SAMPLE_ENV_VAR3: << parameters.envvar3 >>
        steps:
          - run: |
              env | grep -e "^SAMPLE_ENV_VAR.*$"
          - bundler-preamble
    executors:
      default:
        docker:
          - image: cimg/ruby:3.2


workflows:
  sample-workflow:
    jobs:
      - cit/rspec-run:
          # contains FOO env var
          context: foo-1
          envvar1: "test"
          envvar2: "cannot-be-a-sensitive-value"
          envvar3: "fizzbuzz"
